process flowspec-api {
    run /usr/local/bin/flowspec-api.py;
    encoder text;
}

neighbor 10.0.3.1 {
    router-id 10.0.3.10;
    local-address 10.0.3.10;
    local-as 65002;
    peer-as 65001;

    family {
        ipv4 unicast;
        ipv4 flow;
    }

    api {
        processes [ flowspec-api ];
    }
}
